name: '${name}'
version: '${version}'
# noinspection PluginYml
main: '${main}'
api-version: '${apiVersion}'
load: POSTWORLD
author: Matt5262
description: A management plugin for Minecraft Events.
website: https://github.com/Matt5262/MCEManager
