name: MSEManager
version: '${version}'

main: com.matt5262.mSEManager.MSEManager
api-version: '${apiVersion}'
load: POSTWORLD
author: Matt5262
description: A management plugin for Minecraft Events.
website: https://github.com/matt5262/MSEManager
